Repository ava-labs/builders-hub, pull requests merged in 2023-06, with the labels that each got.

#1360 docs: Avalanche consensus rewrite
  docs/learn/avalanche/avalanche-consensus.md
  docs/learn/avalanche/avax.md
Labels: DO NOT MERGE

#1377 Removing Mixed Query Flags
  docs/nodes/maintain/avalanchego-config-flags.md
  docs/nodes/maintain/subnet-configs.md
Labels: DO NOT MERGE, release

#1405 Mixed query deprecation
  docs/nodes/maintain/avalanchego-config-flags.md
  docs/nodes/maintain/subnet-configs.md
Labels: release
