Repository ava-labs/builders-hub, pull requests merged in 2024-11, with the labels that each got.

#1929 Validator Manager Docs + Cleanup
  .github/linkChecker.ts
  app/(home)/page.client.tsx
  app/layout.config.tsx
  components/mermaid.tsx
  content/docs/avalanche-l1s/add-utility/cross-chain-bridge.mdx
  content/docs/avalanche-l1s/elastic-avalanche-l1s/make-avalanche-l1-permissionless.mdx
  content/docs/avalanche-l1s/elastic-avalanche-l1s/parameters.mdx
  content/docs/avalanche-l1s/meta.json
  content/docs/avalanche-l1s/upgrade/customize-avalanche-l1.mdx
  content/docs/dapps/c-chain-or-avalanche-l1.mdx
  content/docs/dapps/meta.json
  content/docs/evm-l1s/custom-precompiles/background-requirements.mdx
  content/docs/evm-l1s/custom-precompiles/defining-precompile.mdx
  content/docs/evm-l1s/custom-precompiles/deploying-precompile.mdx
  content/docs/evm-l1s/custom-precompiles/executing-test-cases.mdx
  content/docs/evm-l1s/custom-precompiles/generating-your-precompile.mdx
  content/docs/evm-l1s/custom-precompiles/introduction.mdx
  content/docs/evm-l1s/custom-precompiles/writing-test-cases.mdx
  content/docs/evm-l1s/default-precompiles/allowlist.mdx
  content/docs/evm-l1s/default-precompiles/feemanager.mdx
  content/docs/evm-l1s/default-precompiles/nativeminter.mdx
  content/docs/evm-l1s/default-precompiles/overview.mdx
  content/docs/evm-l1s/default-precompiles/rewardmanager.mdx
  content/docs/evm-l1s/default-precompiles/warpmessenger.mdx
  content/docs/evm-l1s/index.mdx
  content/docs/evm-l1s/meta.json
  content/docs/evm-l1s/validator-manager/add-validator.mdx
  content/docs/evm-l1s/validator-manager/contract.mdx
  content/docs/evm-l1s/validator-manager/custom-validator-manager.mdx
  content/docs/evm-l1s/validator-manager/remove-validator.mdx
  content/docs/evm-l1s/validator-manager/upgrade.mdx
  content/docs/nodes/on-third-party-services/microsoft-azure.mdx
  content/docs/protocol/avalanche-community-proposals.mdx
  content/docs/protocol/avalanche-consensus.mdx
  content/docs/protocol/avalanche-l1s.mdx
  content/docs/protocol/avax-token.mdx
  content/docs/protocol/c-chain-or-avalanche-l1.mdx
  content/docs/protocol/disclaimer.mdx
  content/docs/protocol/index.mdx
  content/docs/protocol/meta.json
  content/docs/protocol/networks/fuji-testnet.mdx
  content/docs/protocol/networks/mainnet.mdx
  content/docs/protocol/primary-network.mdx
  content/docs/protocol/rewards-formula.mdx
  content/docs/protocol/virtual-machines.mdx
  content/docs/virtual-machines/meta.json
  content/integrations/goldrush.mdx
  mdx-components.tsx
  next.config.mjs
  package.json
Labels: DO NOT MERGE

#1939 Clean Up Navbar
  app/(home)/layout.tsx
  app/(home)/page.client.tsx
  app/(home)/page.tsx
  app/integrations/layout.tsx
  app/layout.client.tsx
  app/layout.config.tsx
Labels: DO NOT MERGE

#1956 Etna Content (PoA vs PoS / Intro to ValidatorManager)
  content/docs/evm-l1s/meta.json
  content/docs/evm-l1s/validator-manager/poa-vs-pos.mdx
  content/docs/protocol/meta.json
  content/docs/protocol/validator-manager.mdx
Labels: 9000

#1936 CLI Docs Consolidation and Update For E-Upgrade
  content/docs/avalanche-l1s/build-first-avalanche-l1.mdx
  content/docs/avalanche-l1s/deploy-a-avalanche-l1/fuji-testnet.mdx
  content/docs/avalanche-l1s/maintain/add-validator-l1.mdx
  content/docs/avalanche-l1s/maintain/remove-validator-l1.mdx
  content/docs/avalanche-l1s/maintain/view-avalanche-l1s.mdx
  content/docs/avalanche-l1s/meta.json
  content/docs/tooling/avalanche-cli.mdx
Labels: DO NOT MERGE, 9000

#1957 remove old api docs and add new remote links
  content/docs/api-reference/admin-api.mdx
  content/docs/api-reference/health-api.mdx
  content/docs/api-reference/index-api.mdx
  content/docs/api-reference/info-api.mdx
  content/docs/api-reference/keystore-api.mdx
  content/docs/api-reference/metrics-api.mdx
  content/docs/api-reference/p-chain/api.mdx
  utils/remote-content.mts
Labels: 9000
